export const CARD_TRADER_SERVICE_NAME = "Card Trader";

export function slugifyCardTraderValue(value) {
  if (!value) return "";

  return String(value)
    .toLowerCase()
    .replace(/[\s._/()"']+/g, "-")
    .replace(/[^a-z0-9-]/g, "")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

export function normalizeCardTraderSetCode(code) {
  if (!code) return "";

  const normalizedCode = String(code).trim().toLowerCase();
  const match = normalizedCode.match(/^([a-z]+)-?(\d{1,3})$/);
  if (!match) {
    return normalizedCode
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
  }

  const letters = match[1];
  const digits = match[2].padStart(2, "0");
  return `${letters}-${digits}`;
}

export function buildCardTraderSetSlug(setName) {
  if (!setName) return "";

  if (setName === "ONE PIECE CARD THE BEST [PRB-01]") {
    return "prb-01-the-best-premium-booster";
  }

  if (setName === "ONE PIECE CARD THE BEST vol.2 [PRB-02]") {
    return "prb-02-the-best-2-premium-booster";
  }

  const setMatch = String(setName).match(/\[([^\]]+)\]/);
  const setCode = setMatch ? normalizeCardTraderSetCode(setMatch[1]) : "";
  const setText = String(setName)
    .replace(/\[[^\]]+\]/, "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

  return setCode ? `${setCode}-${setText}` : setText;
}

export function getCardTraderRaritySlug(rarity) {
  const normalizedRarity = String(rarity ?? "").trim().toLowerCase();

  switch (normalizedRarity) {
    case "sec":
      return "secret-rare";
    case "sp card":
    case "special":
    case "sp":
      return "special-rare";
    case "tr":
      return "treasure-rare";
    default:
      return null;
  }
}

export function getCardTraderIllustrationSlug(illustration) {
  const normalizedIllustration = String(illustration ?? "").trim().toLowerCase();

  switch (normalizedIllustration) {
    case "wanted":
      return "wanted";
    case "manga":
      return "manga-panel-alternate-art";
    case "alternate-art":
      return "alternate-art";
    case "jolly-roger-foil":
      return "jolly-roger-foil";
    default:
      return normalizedIllustration || null;
  }
}

export function buildCardTraderCardUrl(card) {
  if (!card || typeof card !== "object") return null;

  const nameSlug = slugifyCardTraderValue(card.name);
  const setSlug = buildCardTraderSetSlug(card.setName);
  const raritySlug = getCardTraderRaritySlug(card.rarity);
  const illustrationSlug = getCardTraderIllustrationSlug(card.illustration);

  if (!nameSlug) return null;

  let slug = nameSlug;
  if (raritySlug) slug += `-${raritySlug}`;
  if (illustrationSlug) slug += `-${illustrationSlug}`;
  if (setSlug) slug += `-${setSlug}`;

  return `https://www.cardtrader.com/cards/${slug}`;
}

export function ensureCardTraderSlug(card, options = {}) {
  if (!card || typeof card !== "object") return card;

  const url = buildCardTraderCardUrl(card);
  if (!url) return card;

  const nextSlugs = Array.isArray(card.slugs) ? [...card.slugs] : [];
  const existingIndex = nextSlugs.findIndex(
    (entry) => String(entry?.service ?? "") === CARD_TRADER_SERVICE_NAME,
  );
  const nextEntry = {
    service: CARD_TRADER_SERVICE_NAME,
    url,
    verified: Boolean(options.verified),
    autoGenerated: true,
  };

  if (existingIndex >= 0) {
    nextSlugs[existingIndex] = {
      ...nextSlugs[existingIndex],
      url,
      autoGenerated: true,
      verified: options.preserveVerified && nextSlugs[existingIndex]?.verified
        ? true
        : Boolean(options.verified),
    };
  } else {
    nextSlugs.push(nextEntry);
  }

  return {
    ...card,
    slugs: nextSlugs,
  };
}
