create table "public"."brands" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "website" text,
    "logo_url" text not null
);


alter table "public"."currencies" disable row level security;

alter table "public"."games" add column "brand" bigint;

alter table "public"."games" add column "logo_url" text;

alter table "public"."games" add column "slug" text not null;

alter table "public"."games" add column "website" text;

alter table "public"."games" disable row level security;

alter table "public"."languages" disable row level security;

alter table "public"."products" add column "discount_price" text;

alter table "public"."products" disable row level security;

alter table "public"."sets" add column "image_url" text;

alter table "public"."sets" add column "publish_date" date;

alter table "public"."sets" alter column "game" set not null;

alter table "public"."sets" disable row level security;

alter table "public"."stores" add column "discount_selector" text;

CREATE UNIQUE INDEX brands_pkey ON public.brands USING btree (id);

CREATE UNIQUE INDEX games_slug_key ON public.games USING btree (slug);

alter table "public"."brands" add constraint "brands_pkey" PRIMARY KEY using index "brands_pkey";

alter table "public"."games" add constraint "games_brand_fkey" FOREIGN KEY (brand) REFERENCES brands(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."games" validate constraint "games_brand_fkey";

alter table "public"."games" add constraint "games_slug_key" UNIQUE using index "games_slug_key";

grant delete on table "public"."brands" to "anon";

grant insert on table "public"."brands" to "anon";

grant references on table "public"."brands" to "anon";

grant select on table "public"."brands" to "anon";

grant trigger on table "public"."brands" to "anon";

grant truncate on table "public"."brands" to "anon";

grant update on table "public"."brands" to "anon";

grant delete on table "public"."brands" to "authenticated";

grant insert on table "public"."brands" to "authenticated";

grant references on table "public"."brands" to "authenticated";

grant select on table "public"."brands" to "authenticated";

grant trigger on table "public"."brands" to "authenticated";

grant truncate on table "public"."brands" to "authenticated";

grant update on table "public"."brands" to "authenticated";

grant delete on table "public"."brands" to "service_role";

grant insert on table "public"."brands" to "service_role";

grant references on table "public"."brands" to "service_role";

grant select on table "public"."brands" to "service_role";

grant trigger on table "public"."brands" to "service_role";

grant truncate on table "public"."brands" to "service_role";

grant update on table "public"."brands" to "service_role";

create policy "Insert for all"
on "public"."products"
as permissive
for insert
to public
with check (true);


create policy "Update a tutti"
on "public"."products"
as permissive
for update
to public
using (true)
with check (true);


create policy "Insert for all"
on "public"."stores"
as permissive
for insert
to public
with check (true);


create policy "Update for all"
on "public"."stores"
as permissive
for update
to public
using (true)
with check (true);




