create type "public"."container_type" as enum ('album', 'wishlist', 'deck', 'trade');

create table "public"."albums" (
    "user_uuid" uuid not null,
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "id" bigint generated by default as identity not null,
    "slug" text not null,
    "slots" integer not null default 12
);


create table "public"."card_album" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "album_id" bigint,
    "card_id" bigint,
    "index" integer
);


CREATE UNIQUE INDEX card_container_pkey ON public.card_album USING btree (id);

CREATE UNIQUE INDEX containers_pkey ON public.albums USING btree (id);

alter table "public"."albums" add constraint "containers_pkey" PRIMARY KEY using index "containers_pkey";

alter table "public"."card_album" add constraint "card_container_pkey" PRIMARY KEY using index "card_container_pkey";

alter table "public"."albums" add constraint "containers_user_uuid_fkey" FOREIGN KEY (user_uuid) REFERENCES auth.users(id) not valid;

alter table "public"."albums" validate constraint "containers_user_uuid_fkey";

alter table "public"."card_album" add constraint "card_album_album_id_fkey" FOREIGN KEY (album_id) REFERENCES albums(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."card_album" validate constraint "card_album_album_id_fkey";

alter table "public"."card_album" add constraint "card_container_card_id_fkey" FOREIGN KEY (card_id) REFERENCES collection(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."card_album" validate constraint "card_container_card_id_fkey";

grant delete on table "public"."albums" to "anon";

grant insert on table "public"."albums" to "anon";

grant references on table "public"."albums" to "anon";

grant select on table "public"."albums" to "anon";

grant trigger on table "public"."albums" to "anon";

grant truncate on table "public"."albums" to "anon";

grant update on table "public"."albums" to "anon";

grant delete on table "public"."albums" to "authenticated";

grant insert on table "public"."albums" to "authenticated";

grant references on table "public"."albums" to "authenticated";

grant select on table "public"."albums" to "authenticated";

grant trigger on table "public"."albums" to "authenticated";

grant truncate on table "public"."albums" to "authenticated";

grant update on table "public"."albums" to "authenticated";

grant delete on table "public"."albums" to "service_role";

grant insert on table "public"."albums" to "service_role";

grant references on table "public"."albums" to "service_role";

grant select on table "public"."albums" to "service_role";

grant trigger on table "public"."albums" to "service_role";

grant truncate on table "public"."albums" to "service_role";

grant update on table "public"."albums" to "service_role";

grant delete on table "public"."card_album" to "anon";

grant insert on table "public"."card_album" to "anon";

grant references on table "public"."card_album" to "anon";

grant select on table "public"."card_album" to "anon";

grant trigger on table "public"."card_album" to "anon";

grant truncate on table "public"."card_album" to "anon";

grant update on table "public"."card_album" to "anon";

grant delete on table "public"."card_album" to "authenticated";

grant insert on table "public"."card_album" to "authenticated";

grant references on table "public"."card_album" to "authenticated";

grant select on table "public"."card_album" to "authenticated";

grant trigger on table "public"."card_album" to "authenticated";

grant truncate on table "public"."card_album" to "authenticated";

grant update on table "public"."card_album" to "authenticated";

grant delete on table "public"."card_album" to "service_role";

grant insert on table "public"."card_album" to "service_role";

grant references on table "public"."card_album" to "service_role";

grant select on table "public"."card_album" to "service_role";

grant trigger on table "public"."card_album" to "service_role";

grant truncate on table "public"."card_album" to "service_role";

grant update on table "public"."card_album" to "service_role";


