create table "public"."cards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "card_id" text not null,
    "cardtrader_avg_price" numeric,
    "cardmarket_avg_price" numeric,
    "cardtrader_link" text,
    "cardmarket_link" text
);


create table "public"."collection" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_uuid" uuid default auth.uid(),
    "card_number" integer,
    "card_id" text
);


CREATE UNIQUE INDEX cards_card_id_key ON public.cards USING btree (card_id);

CREATE UNIQUE INDEX cards_pkey ON public.cards USING btree (id);

CREATE UNIQUE INDEX collection_pkey ON public.collection USING btree (id);

alter table "public"."cards" add constraint "cards_pkey" PRIMARY KEY using index "cards_pkey";

alter table "public"."collection" add constraint "collection_pkey" PRIMARY KEY using index "collection_pkey";

alter table "public"."cards" add constraint "cards_card_id_key" UNIQUE using index "cards_card_id_key";

alter table "public"."collection" add constraint "collection_card_id_fkey" FOREIGN KEY (card_id) REFERENCES cards(card_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."collection" validate constraint "collection_card_id_fkey";

alter table "public"."collection" add constraint "collection_user_uuid_fkey" FOREIGN KEY (user_uuid) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."collection" validate constraint "collection_user_uuid_fkey";

grant delete on table "public"."cards" to "anon";

grant insert on table "public"."cards" to "anon";

grant references on table "public"."cards" to "anon";

grant select on table "public"."cards" to "anon";

grant trigger on table "public"."cards" to "anon";

grant truncate on table "public"."cards" to "anon";

grant update on table "public"."cards" to "anon";

grant delete on table "public"."cards" to "authenticated";

grant insert on table "public"."cards" to "authenticated";

grant references on table "public"."cards" to "authenticated";

grant select on table "public"."cards" to "authenticated";

grant trigger on table "public"."cards" to "authenticated";

grant truncate on table "public"."cards" to "authenticated";

grant update on table "public"."cards" to "authenticated";

grant delete on table "public"."cards" to "service_role";

grant insert on table "public"."cards" to "service_role";

grant references on table "public"."cards" to "service_role";

grant select on table "public"."cards" to "service_role";

grant trigger on table "public"."cards" to "service_role";

grant truncate on table "public"."cards" to "service_role";

grant update on table "public"."cards" to "service_role";

grant delete on table "public"."collection" to "anon";

grant insert on table "public"."collection" to "anon";

grant references on table "public"."collection" to "anon";

grant select on table "public"."collection" to "anon";

grant trigger on table "public"."collection" to "anon";

grant truncate on table "public"."collection" to "anon";

grant update on table "public"."collection" to "anon";

grant delete on table "public"."collection" to "authenticated";

grant insert on table "public"."collection" to "authenticated";

grant references on table "public"."collection" to "authenticated";

grant select on table "public"."collection" to "authenticated";

grant trigger on table "public"."collection" to "authenticated";

grant truncate on table "public"."collection" to "authenticated";

grant update on table "public"."collection" to "authenticated";

grant delete on table "public"."collection" to "service_role";

grant insert on table "public"."collection" to "service_role";

grant references on table "public"."collection" to "service_role";

grant select on table "public"."collection" to "service_role";

grant trigger on table "public"."collection" to "service_role";

grant truncate on table "public"."collection" to "service_role";

grant update on table "public"."collection" to "service_role";


