create type "public"."visibility" as enum ('public', 'private', 'friends');

create table "public"."deck_cards" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "deck_id" bigint not null,
    "card_id" bigint not null,
    "card_number" integer not null
);


alter table "public"."deck_cards" enable row level security;

create table "public"."decks" (
    "id" bigint generated by default as identity not null,
    "user_uuid" uuid default auth.uid(),
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "slug" text not null,
    "cards" jsonb[],
    "leader" text,
    "visibility" visibility not null default 'public'::visibility
);


alter table "public"."albums" add column "visibility" visibility not null default 'public'::visibility;

drop type "public"."container_type";

CREATE UNIQUE INDEX deck_cards_pkey ON public.deck_cards USING btree (id);

CREATE UNIQUE INDEX decks_pkey ON public.decks USING btree (id);

alter table "public"."deck_cards" add constraint "deck_cards_pkey" PRIMARY KEY using index "deck_cards_pkey";

alter table "public"."decks" add constraint "decks_pkey" PRIMARY KEY using index "decks_pkey";

alter table "public"."deck_cards" add constraint "deck_cards_card_id_fkey" FOREIGN KEY (card_id) REFERENCES cards(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."deck_cards" validate constraint "deck_cards_card_id_fkey";

alter table "public"."deck_cards" add constraint "deck_cards_deck_id_fkey" FOREIGN KEY (deck_id) REFERENCES decks(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."deck_cards" validate constraint "deck_cards_deck_id_fkey";

grant delete on table "public"."deck_cards" to "anon";

grant insert on table "public"."deck_cards" to "anon";

grant references on table "public"."deck_cards" to "anon";

grant select on table "public"."deck_cards" to "anon";

grant trigger on table "public"."deck_cards" to "anon";

grant truncate on table "public"."deck_cards" to "anon";

grant update on table "public"."deck_cards" to "anon";

grant delete on table "public"."deck_cards" to "authenticated";

grant insert on table "public"."deck_cards" to "authenticated";

grant references on table "public"."deck_cards" to "authenticated";

grant select on table "public"."deck_cards" to "authenticated";

grant trigger on table "public"."deck_cards" to "authenticated";

grant truncate on table "public"."deck_cards" to "authenticated";

grant update on table "public"."deck_cards" to "authenticated";

grant delete on table "public"."deck_cards" to "service_role";

grant insert on table "public"."deck_cards" to "service_role";

grant references on table "public"."deck_cards" to "service_role";

grant select on table "public"."deck_cards" to "service_role";

grant trigger on table "public"."deck_cards" to "service_role";

grant truncate on table "public"."deck_cards" to "service_role";

grant update on table "public"."deck_cards" to "service_role";

grant delete on table "public"."decks" to "anon";

grant insert on table "public"."decks" to "anon";

grant references on table "public"."decks" to "anon";

grant select on table "public"."decks" to "anon";

grant trigger on table "public"."decks" to "anon";

grant truncate on table "public"."decks" to "anon";

grant update on table "public"."decks" to "anon";

grant delete on table "public"."decks" to "authenticated";

grant insert on table "public"."decks" to "authenticated";

grant references on table "public"."decks" to "authenticated";

grant select on table "public"."decks" to "authenticated";

grant trigger on table "public"."decks" to "authenticated";

grant truncate on table "public"."decks" to "authenticated";

grant update on table "public"."decks" to "authenticated";

grant delete on table "public"."decks" to "service_role";

grant insert on table "public"."decks" to "service_role";

grant references on table "public"."decks" to "service_role";

grant select on table "public"."decks" to "service_role";

grant trigger on table "public"."decks" to "service_role";

grant truncate on table "public"."decks" to "service_role";

grant update on table "public"."decks" to "service_role";


