create table "public"."collection" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_uuid" uuid default auth.uid(),
    "card_number" integer,
    "card_id" text
);


CREATE UNIQUE INDEX collection_pkey ON public.collection USING btree (id);

alter table "public"."collection" add constraint "collection_pkey" PRIMARY KEY using index "collection_pkey";

alter table "public"."collection" add constraint "collection_user_uuid_fkey" FOREIGN KEY (user_uuid) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."collection" validate constraint "collection_user_uuid_fkey";

grant delete on table "public"."collection" to "anon";

grant insert on table "public"."collection" to "anon";

grant references on table "public"."collection" to "anon";

grant select on table "public"."collection" to "anon";

grant trigger on table "public"."collection" to "anon";

grant truncate on table "public"."collection" to "anon";

grant update on table "public"."collection" to "anon";

grant delete on table "public"."collection" to "authenticated";

grant insert on table "public"."collection" to "authenticated";

grant references on table "public"."collection" to "authenticated";

grant select on table "public"."collection" to "authenticated";

grant trigger on table "public"."collection" to "authenticated";

grant truncate on table "public"."collection" to "authenticated";

grant update on table "public"."collection" to "authenticated";

grant delete on table "public"."collection" to "service_role";

grant insert on table "public"."collection" to "service_role";

grant references on table "public"."collection" to "service_role";

grant select on table "public"."collection" to "service_role";

grant trigger on table "public"."collection" to "service_role";

grant truncate on table "public"."collection" to "service_role";

grant update on table "public"."collection" to "service_role";

