create type "public"."visibility" as enum ('public', 'private', 'friends');

create table "public"."decks" (
    "id" bigint generated by default as identity not null,
    "user_uuid" uuid default auth.uid(),
    "name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "slug" text not null,
    "cards" jsonb[],
    "leader" text,
    "visibility" visibility not null default 'public'::visibility
);


alter table "public"."albums" add column "visibility" visibility not null default 'public'::visibility;

drop type "public"."container_type";

CREATE UNIQUE INDEX decks_pkey ON public.decks USING btree (id);

alter table "public"."decks" add constraint "decks_pkey" PRIMARY KEY using index "decks_pkey";

grant delete on table "public"."decks" to "anon";

grant insert on table "public"."decks" to "anon";

grant references on table "public"."decks" to "anon";

grant select on table "public"."decks" to "anon";

grant trigger on table "public"."decks" to "anon";

grant truncate on table "public"."decks" to "anon";

grant update on table "public"."decks" to "anon";

grant delete on table "public"."decks" to "authenticated";

grant insert on table "public"."decks" to "authenticated";

grant references on table "public"."decks" to "authenticated";

grant select on table "public"."decks" to "authenticated";

grant trigger on table "public"."decks" to "authenticated";

grant truncate on table "public"."decks" to "authenticated";

grant update on table "public"."decks" to "authenticated";

grant delete on table "public"."decks" to "service_role";

grant insert on table "public"."decks" to "service_role";

grant references on table "public"."decks" to "service_role";

grant select on table "public"."decks" to "service_role";

grant trigger on table "public"."decks" to "service_role";

grant truncate on table "public"."decks" to "service_role";

grant update on table "public"."decks" to "service_role";

