create table "public"."categories" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text
);


alter table "public"."products" drop column "discount_price";

alter table "public"."products" drop column "price";

alter table "public"."products" add column "category" bigint;

alter table "public"."products" add column "discounted_price" numeric;

alter table "public"."products" add column "original_price" numeric;

alter table "public"."products" add column "regular_price" numeric;

alter table "public"."stores" drop column "discount_selector";

alter table "public"."stores" drop column "price_selector";

alter table "public"."stores" add column "discounted_price_selector" text;

alter table "public"."stores" add column "original_price_selector" text;

alter table "public"."stores" add column "regular_price_selector" text;

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (id);

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."products" add constraint "products_category_fkey" FOREIGN KEY (category) REFERENCES categories(id) not valid;

alter table "public"."products" validate constraint "products_category_fkey";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";



