DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type t
    JOIN pg_namespace n ON n.oid = t.typnamespace
    WHERE n.nspname = 'public'
      AND t.typname = 'offer_status'
  ) THEN
    CREATE TYPE public.offer_status AS ENUM ('Pending', 'Accepted', 'Rejected');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.offer_listing (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  sell_list_id bigint not null,
  offer numeric not null default 0,
  quantity integer not null default 0,
  status public.offer_status not null default 'Pending'::public.offer_status,
  offerer_id uuid not null default auth.uid()
);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'offer_listing'
      AND pg_get_userbyid(c.relowner) = current_user
  ) THEN
    ALTER TABLE public.offer_listing ENABLE ROW LEVEL SECURITY;

    CREATE UNIQUE INDEX IF NOT EXISTS offer_listing_pkey ON public.offer_listing USING btree (id);

    IF NOT EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conname = 'offer_listing_pkey'
        AND conrelid = 'public.offer_listing'::regclass
    ) THEN
      ALTER TABLE public.offer_listing
      ADD CONSTRAINT offer_listing_pkey PRIMARY KEY USING INDEX offer_listing_pkey;
    END IF;

    GRANT DELETE ON TABLE public.offer_listing TO anon;
    GRANT INSERT ON TABLE public.offer_listing TO anon;
    GRANT REFERENCES ON TABLE public.offer_listing TO anon;
    GRANT SELECT ON TABLE public.offer_listing TO anon;
    GRANT TRIGGER ON TABLE public.offer_listing TO anon;
    GRANT TRUNCATE ON TABLE public.offer_listing TO anon;
    GRANT UPDATE ON TABLE public.offer_listing TO anon;

    GRANT DELETE ON TABLE public.offer_listing TO authenticated;
    GRANT INSERT ON TABLE public.offer_listing TO authenticated;
    GRANT REFERENCES ON TABLE public.offer_listing TO authenticated;
    GRANT SELECT ON TABLE public.offer_listing TO authenticated;
    GRANT TRIGGER ON TABLE public.offer_listing TO authenticated;
    GRANT TRUNCATE ON TABLE public.offer_listing TO authenticated;
    GRANT UPDATE ON TABLE public.offer_listing TO authenticated;

    GRANT DELETE ON TABLE public.offer_listing TO postgres;
    GRANT INSERT ON TABLE public.offer_listing TO postgres;
    GRANT REFERENCES ON TABLE public.offer_listing TO postgres;
    GRANT SELECT ON TABLE public.offer_listing TO postgres;
    GRANT TRIGGER ON TABLE public.offer_listing TO postgres;
    GRANT TRUNCATE ON TABLE public.offer_listing TO postgres;
    GRANT UPDATE ON TABLE public.offer_listing TO postgres;

    GRANT DELETE ON TABLE public.offer_listing TO service_role;
    GRANT INSERT ON TABLE public.offer_listing TO service_role;
    GRANT REFERENCES ON TABLE public.offer_listing TO service_role;
    GRANT SELECT ON TABLE public.offer_listing TO service_role;
    GRANT TRIGGER ON TABLE public.offer_listing TO service_role;
    GRANT TRUNCATE ON TABLE public.offer_listing TO service_role;
    GRANT UPDATE ON TABLE public.offer_listing TO service_role;
  END IF;
END $$;
