CREATE TABLE IF NOT EXISTS public.offer_listing_chat_messages (
  id bigint generated by default as identity not null,
  offer_listing_id bigint not null,
  sender_id uuid not null default auth.uid(),
  body text not null,
  seen_at timestamp with time zone null,
  created_at timestamp with time zone not null default now()
);

ALTER TABLE public.offer_listing_chat_messages ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX IF NOT EXISTS offer_listing_chat_messages_pkey
  ON public.offer_listing_chat_messages USING btree (id);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'offer_listing_chat_messages_pkey'
      AND conrelid = 'public.offer_listing_chat_messages'::regclass
  ) THEN
    ALTER TABLE public.offer_listing_chat_messages
      ADD CONSTRAINT offer_listing_chat_messages_pkey
      PRIMARY KEY USING INDEX offer_listing_chat_messages_pkey;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'offer_listing_chat_messages_offer_listing_id_fkey'
      AND conrelid = 'public.offer_listing_chat_messages'::regclass
  ) THEN
    ALTER TABLE public.offer_listing_chat_messages
      ADD CONSTRAINT offer_listing_chat_messages_offer_listing_id_fkey
      FOREIGN KEY (offer_listing_id)
      REFERENCES public.offer_listing(id)
      ON UPDATE CASCADE
      ON DELETE CASCADE
      NOT VALID;

    ALTER TABLE public.offer_listing_chat_messages
      VALIDATE CONSTRAINT offer_listing_chat_messages_offer_listing_id_fkey;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'offer_listing_chat_messages_sender_id_fkey'
      AND conrelid = 'public.offer_listing_chat_messages'::regclass
  ) THEN
    ALTER TABLE public.offer_listing_chat_messages
      ADD CONSTRAINT offer_listing_chat_messages_sender_id_fkey
      FOREIGN KEY (sender_id)
      REFERENCES auth.users(id)
      ON UPDATE CASCADE
      ON DELETE CASCADE
      NOT VALID;

    ALTER TABLE public.offer_listing_chat_messages
      VALIDATE CONSTRAINT offer_listing_chat_messages_sender_id_fkey;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'offer_listing_chat_messages_body_not_blank_check'
      AND conrelid = 'public.offer_listing_chat_messages'::regclass
  ) THEN
    ALTER TABLE public.offer_listing_chat_messages
      ADD CONSTRAINT offer_listing_chat_messages_body_not_blank_check
      CHECK (char_length(btrim(body)) > 0);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS offer_listing_chat_messages_offer_listing_created_at_idx
  ON public.offer_listing_chat_messages USING btree (offer_listing_id, created_at);

CREATE INDEX IF NOT EXISTS offer_listing_chat_messages_offer_listing_unseen_idx
  ON public.offer_listing_chat_messages USING btree (offer_listing_id, seen_at)
  WHERE seen_at IS NULL;
