create type "public"."sell_listing_status" as enum ('active', 'sold', 'cancelled');

create table "public"."sell_listings" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "card_id" text not null,
    "seller_uuid" uuid not null default auth.uid(),
    "latitude" double precision not null,
    "longitude" double precision not null,
    "quantity" integer not null,
    "price" numeric(12,2) not null,
    "status" sell_listing_status not null default 'active'::sell_listing_status
);

alter table "public"."sell_listings" enable row level security;

CREATE UNIQUE INDEX sell_listings_pkey ON public.sell_listings USING btree (id);
CREATE INDEX sell_listings_active_card_idx ON public.sell_listings USING btree (card_id) WHERE (status = 'active'::sell_listing_status);
CREATE INDEX sell_listings_active_seller_idx ON public.sell_listings USING btree (seller_uuid) WHERE (status = 'active'::sell_listing_status);

alter table "public"."sell_listings" add constraint "sell_listings_pkey" PRIMARY KEY using index "sell_listings_pkey";

alter table "public"."sell_listings" add constraint "sell_listings_card_id_fkey" FOREIGN KEY (card_id) REFERENCES cards(card_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."sell_listings" validate constraint "sell_listings_card_id_fkey";

alter table "public"."sell_listings" add constraint "sell_listings_seller_uuid_fkey" FOREIGN KEY (seller_uuid) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;
alter table "public"."sell_listings" validate constraint "sell_listings_seller_uuid_fkey";

alter table "public"."sell_listings" add constraint "sell_listings_latitude_check" CHECK ((latitude >= (-90)::double precision) AND (latitude <= (90)::double precision));
alter table "public"."sell_listings" add constraint "sell_listings_longitude_check" CHECK ((longitude >= (-180)::double precision) AND (longitude <= (180)::double precision));
alter table "public"."sell_listings" add constraint "sell_listings_quantity_check" CHECK (quantity > 0);
alter table "public"."sell_listings" add constraint "sell_listings_price_check" CHECK (price > 0);

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.set_sell_listing_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.enforce_sell_listing_stock()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = public
AS $function$
declare
  owned_qty integer;
  active_listed_qty integer;
begin
  select coalesce(sum(c.card_number), 0)
  into owned_qty
  from public.collection c
  where c.user_uuid = new.seller_uuid
    and c.card_id = new.card_id;

  if owned_qty = 0 then
    raise exception 'Card % is not present in seller collection', new.card_id;
  end if;

  if new.status = 'active'::public.sell_listing_status then
    select coalesce(sum(ml.quantity), 0)
    into active_listed_qty
    from public.sell_listings ml
    where ml.seller_uuid = new.seller_uuid
      and ml.card_id = new.card_id
      and ml.status = 'active'::public.sell_listing_status
      and (tg_op = 'INSERT' or ml.id <> new.id);

    if (active_listed_qty + new.quantity) > owned_qty then
      raise exception 'Active listings quantity (%) exceeds owned quantity (%) for card %',
        (active_listed_qty + new.quantity), owned_qty, new.card_id;
    end if;
  end if;

  return new;
end;
$function$
;

create trigger "trg_sell_listings_set_updated_at"
before update on "public"."sell_listings"
for each row
execute function "public"."set_sell_listing_updated_at"();

create trigger "trg_sell_listings_enforce_stock"
before insert or update on "public"."sell_listings"
for each row
execute function "public"."enforce_sell_listing_stock"();

create policy "sell listings are readable by all"
on "public"."sell_listings"
as permissive
for select
to public
using ((status = 'active'::sell_listing_status) OR (seller_uuid = auth.uid()));

create policy "Authenticated users can create own listings"
on "public"."sell_listings"
as permissive
for insert
to authenticated
with check ((seller_uuid = auth.uid()));

create policy "Authenticated users can update own listings"
on "public"."sell_listings"
as permissive
for update
to authenticated
using ((seller_uuid = auth.uid()))
with check ((seller_uuid = auth.uid()));

create policy "Authenticated users can delete own listings"
on "public"."sell_listings"
as permissive
for delete
to authenticated
using ((seller_uuid = auth.uid()));

grant select on table "public"."sell_listings" to "anon";
grant select, insert, update, delete on table "public"."sell_listings" to "authenticated";
grant all on table "public"."sell_listings" to "service_role";

grant usage, select on sequence "public"."sell_listings_id_seq" to "authenticated";
grant usage, select on sequence "public"."sell_listings_id_seq" to "service_role";
