
create table "public"."friends" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp with time zone not null default now(),
  "user_profile" uuid not null default auth.uid(),
  "friend_profile" character varying not null,
  "blocked_at" timestamp with time zone
);


alter table "public"."friends" enable row level security;

CREATE UNIQUE INDEX friends_pkey ON public.friends USING btree (id, user_profile, friend_profile);

alter table "public"."friends" add constraint "friends_pkey" PRIMARY KEY using index "friends_pkey";

grant delete on table "public"."friends" to "anon";

grant insert on table "public"."friends" to "anon";

grant references on table "public"."friends" to "anon";

grant select on table "public"."friends" to "anon";

grant trigger on table "public"."friends" to "anon";

grant truncate on table "public"."friends" to "anon";

grant update on table "public"."friends" to "anon";

grant delete on table "public"."friends" to "authenticated";

grant insert on table "public"."friends" to "authenticated";

grant references on table "public"."friends" to "authenticated";

grant select on table "public"."friends" to "authenticated";

grant trigger on table "public"."friends" to "authenticated";

grant truncate on table "public"."friends" to "authenticated";

grant update on table "public"."friends" to "authenticated";

grant delete on table "public"."friends" to "postgres";

grant insert on table "public"."friends" to "postgres";

grant references on table "public"."friends" to "postgres";

grant select on table "public"."friends" to "postgres";

grant trigger on table "public"."friends" to "postgres";

grant truncate on table "public"."friends" to "postgres";

grant update on table "public"."friends" to "postgres";

grant delete on table "public"."friends" to "service_role";

grant insert on table "public"."friends" to "service_role";

grant references on table "public"."friends" to "service_role";

grant select on table "public"."friends" to "service_role";

grant trigger on table "public"."friends" to "service_role";

grant truncate on table "public"."friends" to "service_role";

grant update on table "public"."friends" to "service_role";


create policy "Friends delete if partecipant"
  on "public"."friends"
  as permissive
  for delete
  to public
using (((auth.uid() = user_profile) OR ((auth.uid())::text = (friend_profile)::text)));



create policy "Friends update if partecipant"
  on "public"."friends"
  as permissive
  for update
  to public
using (((auth.uid() = user_profile) OR ((auth.uid())::text = (friend_profile)::text)));



